// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as FileReading from "./filereading.js";
import * as GreetService from "./greetservice.js";
export {
    FileReading,
    GreetService
};
